### ISSUE TITLE
[amazon-location-samples][maplibre-js-react-iot-asset-tracking]-Can I submit multiple locations in one map update? in lambda

### ISSUE THREAD

**Issue by NguyenDOanNhan** [aws-samples/amazon-location-samples#117]

**Comment by NguyenDOanNhan** [comment]
![2022-02-16_10-20-48](https://user-images.githubusercontent.com/43739331/154189954-5e85cbb1-cc17-4c0c-a15e-58c746cdc1af.png)
ex for location

**Comment by dreamorosi** [comment]
Hello, could you please elaborate more on what are you trying to achieve and where, in relations to the samples, you're finding the issue?

If you're referring to the Lambda function described at [step 5](https://github.com/aws-samples/amazon-location-samples/tree/main/maplibre-js-react-iot-asset-tracking#5-create-an-aws-lambda-function-to-update-your-tracker) of the IoT Tracker sample then yes. The Amazon Location Service tracker's position is updated using the [BatchUpdateDevicePosition](https://docs.aws.amazon.com/location-trackers/latest/APIReference/API_BatchUpdateDevicePosition.html) API which takes up to 10 updates. So the `updates` array in the example:
```js
const updates = [
    {
      DeviceId: event.payload.deviceId,
      SampleTime: new Date(event.payload.timestamp).toISOString(),
      Position: [event.payload.location.long, event.payload.location.lat],
    },
  ];
```
can contain up to 10 objects:
```js
const updates = [
    {
      DeviceId: event.payload.deviceId,
      SampleTime: new Date(event.payload.timestamp).toISOString(),
      Position: [event.payload.location.long, event.payload.location.lat],
    },
    {
      DeviceId: event.payload.deviceId,
      SampleTime: new Date(event.payload.timestamp).toISOString(),
      Position: [event.payload.location.long, event.payload.location.lat],
    },
    // 8 more
  ];
```

While this is possible, the sample has been built to show how to update the tracker one update at the time, so if you want to pass more updates you'll have to refactor both the Lambda function and the [sample code](https://github.com/aws-samples/amazon-location-samples/blob/main/maplibre-js-react-iot-asset-tracking/generate_thing_events/index.js#L30-L38) that sends the event. 

At the moment we are not planning on extending this sample further unless there's some bug or particularly unclear section that needs clarification.

Let me know if this answer your question.

**Comment by NguyenDOanNhan** [comment]
Well thank you very much

**Comment by thehoneymad** [comment]
Hello @NguyenDOanNhan, thank you for reaching out to us! I am closing this issue. If we could be of more help, please let us know. :)
