### ISSUE TITLE
Put Geofance request

### ISSUE THREAD

**Issue by zaher88abd** [aws-samples/amazon-location-samples#16]
Hi There,

This is not an issue, but I was looking for an example to send a request to add geofence in the created collection. I read this [guide ](https://docs.aws.amazon.com/location-geofences/latest/APIReference/location-geofences-api.pdf#Welcome) many times, but I could not figure it out. I will appreciate your help. 
My main issue is sending a request from an Android app, this is my code 
`
val geofenceCollectionName = "NewCollection"
  val geofenceName = "TestAndroid"
  var url: String = "https://%s.geo.%s.amazonaws.com".format("geofencing", "us-east-1")

  url += "/geofencing/v0/collections/%s/geofences/%s".format(geofenceCollectionName, geofenceName)
  Log.i(TAG, "The url $url")

  val polygon = mutableListOf<List<Double>>()

  for (point in pointsList) {
      val doubleList: List<Double> = mutableListOf(point.longitude, point.latitude)
      polygon.add(doubleList)
  }

  val entry = Geometry(mutableListOf(polygon))

  Log.i(TAG, Gson().toJson(entry).toString())

  val accesskeyId = getString(R.string.access_key_id)
  val accessKey = getString(R.string.accessKey)

  Log.i(TAG, "Keys:$accesskeyId,$accessKey")

  val region = "us-east-1"
  val serviceName = "geo"
  val signer = OkHttpAwsV4Signer(region, serviceName)
  val dateStamp = DateTimeFormatter
          .ofPattern("yyyyMMdd'T'HHmmss'Z'")
          .withZone(ZoneOffset.UTC)
          .format(Instant.now())

  val request = Request.Builder()
          .url(url)
          .addHeader("Method", "PUT")
          .addHeader("Content-Type", "application/json")
          .addHeader("x-amz-date", dateStamp)
          .addHeader("Host", "geo.amazonaws.com")
          .put(Gson().toJson(entry).toRequestBody())
          .build()

  val newRequest = signer.sign(request, accesskeyId, accessKey)
`
If I send a request using HTTPS protocol. I am getting a 403 response with the message "message": "Forbidden"", I added full access role to IAM but still not working. 

However, in the guide they said using HTTP/1.1, so is this meaning using HTTP instead of HTTPS. Even though, that didn't work.

I am sorry if this is not the place for this issue, but I need any help.

Thanks in advance.

**Comment by mojodna** [comment]
Your best bet is going to be to use the [AWS SDK for Java](https://aws.amazon.com/sdk-for-java/), specifically [`batchPutGeofence`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/location/LocationClient.html#batchPutGeofence-java.util.function.Consumer-). That will prevent you from needing to deal with the transport and the signing. It will have a slightly different signature for the polygons, but you've got the gist of the polygon generation already.
