### ISSUE TITLE
Sample tracker displays longitude twice

### ISSUE THREAD

**Issue by zachelliottwx** [aws-samples/amazon-location-samples#163]
<img width="190" alt="Screen Shot 2022-06-16 at 11 06 58 AM" src="https://user-images.githubusercontent.com/11575088/174116010-5c905c78-0106-46ad-bdf1-9991a705c020.png">
When updating a tracker either through the simulation in the console or through batch-update-device-position, the longitude is listed twice.

**Comment by imraymondlee** [comment]
Thanks for reporting this, I have created a PR to fix the bug #164
