### ISSUE TITLE
Broken link for react Map apps

### ISSUE THREAD

**Issue by MichaelWalker-git** [aws-samples/amazon-location-samples#185]
Broken links: 

- [Using MapLibre GL JS with Amazon Location Service and AWS Amplify in a React application](https://github.com/aws-samples/amazon-location-samples/blob/main/maplibre-gl-js-react-amplify)

**Comment by dreamorosi** [comment]
Thank you, we have removed that sample in favor of those who use the same components/libraries:
- https://github.com/aws-samples/amazon-location-samples/tree/main/amplify-ui-geo-explore
- https://github.com/aws-samples/amazon-location-samples/tree/main/react-map-gl-change-map-language
- https://github.com/aws-samples/amazon-location-samples/tree/main/react-map-gl-clusters
- https://github.com/aws-samples/amazon-location-samples/tree/main/react-map-gl-map-styles
- https://github.com/aws-samples/amazon-location-samples/tree/main/react-map-gl-markers
- https://github.com/aws-samples/amazon-location-samples/tree/main/react-map-gl-polygons

Will create a PR to remove the link
