### ISSUE TITLE
[maplibre-js-react-iot-asset-tracking] Map and tracker do not display

### ISSUE THREAD

**Issue by digihunch** [aws-samples/amazon-location-samples#189]
I've followed all steps in maplibre-js-react-iot-asset-tracking but the map doesn't display. 

The README file gives wrong port (should be 8080, instead of 3000). Even on port 8080, the web page is still blank.

It has to do with the combination of the followings:
1. At step 3, when creating Map resource, it specifies authorized user only
2. At step 4, after creating tracker, the permission to access tracker is added to unauthRole
3. The App.js code isn't configured to use Authentication at all. Even if it did, the authorized role would not have had access to tracker.

**Comment by zachelliottwx** [comment]
Hi there. Thank you for raising this issue. The maintainers will take a look and get back with you.

**Comment by zachelliottwx** [comment]
Documentation has been fixed https://github.com/aws-samples/amazon-location-samples/pull/190 to reflect the port difference and to create an Auth and Unauth resource using Amplify Geo
