### ISSUE TITLE
Some Europe countries coordinates shows wrong output 

### ISSUE THREAD

**Issue by Rinlama** [aws-samples/amazon-location-samples#195]
Example   {
      type: "Feature",
      properties: {
        time: 1642781317361,
      },
      geometry: {
        type: "Point",
        coordinates: [47.402552, 0.624474],
      },
    }
France coordinates doesn't shows France on map.

**Comment by dreamorosi** [comment]
Hi, which sample are you referring to?

**Comment by Rinlama** [comment]
I tried on React Marker and Cluster sample on both same result shows wrong coordinates on Spain and France.

`const clusterData: any = {
  type: "FeatureCollection",
  metadata: {
    title: "Battery Stock Location",
    count: 3,
  },
  features: [
    {
      type: "Feature",
      properties: {
        time: 1642781317361,
      },
      geometry: {
        type: "Point",
        coordinates: [47.402552, 0.624474],
      },
    },
  ]
};`

**Comment by dreamorosi** [comment]
Can you please share a screenshot?

**Comment by Rinlama** [comment]
Sure, it should shows marker on France, but shows on ocean. https://imgur.com/a/KtYy97c

**Comment by Rinlama** [comment]
Solved. it was wrong position. Thank you for quick response.
