### ISSUE TITLE
Cluster Map Show Count Issues

### ISSUE THREAD

**Issue by Rinlama** [aws-samples/amazon-location-samples#197]
Hello All, 

I got this error CognitoIdentityCredentials is not authorized to perform: geo:GetMapGlyphs even though I added in roles policy.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "geo:GetMap*",
                "geo:GetMapStyleDescriptor",
                "geo:GetMapGlyphs",
                "geo:GetMapSprites",
                "geo:GetMapTile"
            ],
            "Resource": "{resources here}",
            "Condition": {
                "StringLike": {
                    "aws:referer": [
                        "https://www.example.com/*",
                        "http://localhost:*/*"
                    ]
                }
            }
        }
    ]
}
Thank you

**Comment by dreamorosi** [comment]
Hi, if you have access to the AWS console, I would recommend using the IAM console visual editor to create the policy, this way you'll be able to check that the statements are valid.

Alternatively, I would also recommend using the policy shown in the [docs here](https://docs.aws.amazon.com/location/latest/developerguide/how-to-access.html#cognito-create-user-pool):
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "geo:GetMap*",
            "Resource": "arn:aws:geo:us-west-2:111122223333:map/RasterEsriImagery",
            "Condition": {
                "StringLike": {
                    "aws:referer": [
                        "https://example.com/*",
                        "https://www.example.com/*"
                    ]
                }
            }
        }
    ]
}
```

Check specifically the items under `aws:referer` (in the docs they have `/*` at the end), and make sure that in your case - when using `localhost` - you are putting the right port if one is needed (i.e. `http://localhost:1234/*`).

**Comment by Rinlama** [comment]
Thank you for quick response, I did same configuration as you provided, but still has an issues. Does geo:GetMapGlyphs need Auth role's policy in Cognito? I am using unauth roles policy on Cognito Credentials. I also found couple of stackoverflow threads where people are mentioning geo:GetMapGlyphs is only for Auth. If it need Auth Role's, is there any sample in React to do Auth in AWS Amplify?
