### ISSUE TITLE
amazon-location-helpers - broken link in README.md

### ISSUE THREAD

**Issue by Matthew-Kwan** [aws-samples/amazon-location-samples#229]
The example in [this subsection](https://github.com/aws-samples/amazon-location-samples/tree/main/amazon-location-helpers#createrequesttransformer) for a fully worked example of using the `createRequestTransformer` function links to a sample app that was deleted in [this commit](For a fully worked example, see [maplibre-gl-js-react/src/index.tsx](https://github.com/aws-samples/amazon-location-samples/blob/main/maplibre-gl-js-react/src/index.tsx).).

Can we find a new example to share for this particular use case, or if one isn't present, could we revive the old `maplibre-gl-js-react` sample app so that it can serve as such?

**Comment by dreamorosi** [comment]
Hi, thank you for opening the issue.

I would suggest you to look into the `AmplifyMapLibreRequest` class from [`maplibre-gl-js-amplify`](https://github.com/aws-amplify/maplibre-gl-js-amplify) instead. 

That package is actively maintained and requires less heavy lifting & boilerplate code.

You can see an example of how it's used in [this other sample](https://github.com/aws-samples/amazon-location-samples/blob/main/react-map-gl-polygons/src/main.jsx#L61-L63).
Note that this sample uses Amplify to retrieve the credentials ([see this line](https://github.com/aws-samples/amazon-location-samples/blob/main/react-map-gl-polygons/src/main.jsx#L57)), this is **not a requirement** and you can pass a credentials object obtained in any other way (i.e. directly from Cognito like the section you've linked).
