### ISSUE TITLE
Issue when running npm ci

### ISSUE THREAD

**Issue by jedijamez567** [aws-samples/amazon-location-samples#274]
When I run the npm ci command, I get the following error: 

cd amazon-location-samples/maplibre-js-react-iot-asset-tracking
npm ci
Cloning into 'amazon-location-samples'...
remote: Enumerating objects: 3542, done.
remote: Counting objects: 100% (321/321), done.
remote: Compressing objects: 100% (202/202), done.
remote: Total 3542 (delta 169), reused 217 (delta 110), pack-reused 3221
Receiving objects: 100% (3542/3542), 131.67 MiB | 33.92 MiB/s, done.
Resolving deltas: 100% (1862/1862), done.
npm ERR! code EUSAGE
npm ERR! 
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

**Comment by dreamorosi** [comment]
Hi, thanks for opening the issue.

We are in the process of migrating some of the samples to dedicated repositories. The sample that you're having issues with has already been migrated and can be found at its new location here: https://github.com/aws-samples/amazon-location-service-iot-asset-tracking

Please try to clone that repository & work with that version as the one in this repository is about to get archived. If you find issues with the one in the new repo please feel free to open an issue on its repo.

**Comment by jedijamez567** [comment]
Ah thank you!
