### ISSUE TITLE
Question regarding MapLibre iOS/Android SDK + ESRI Maps

### ISSUE THREAD

**Issue by mohitb117** [aws-samples/amazon-location-samples#29]
Hi!
 
While trying out samples for iOS/Android we are seeing some differences in behavior of the android/iOS sdk's for MapLibre. 

The apps are using 

```
       maplibreMap.setStyle(
                Style.Builder()
                    .fromUri("https://maps.geo.${region}.amazonaws.com/maps/v0/maps/${mapName}/style-descriptor")
            )
```

The iOS SDK seems to respect the default device platform settings and gets the right style of map tiles from ALS but the Android SDK doesn't seem to have similar feature parity. 

Ideally this would be controlled by : 
https://docs.mapbox.com/android/maps/guides/styling-map/

```
       maplibreMap.setStyle(Style.LIGHT)


  /**
   * Light: Subtle light backdrop for data visualizations. Using this constant means your map
   * style will always use the latest version and may change as we improve the style.
   */
  public static final String LIGHT = "mapbox://styles/mapbox/light-v10";

  /**
   * Dark: Subtle dark backdrop for data visualizations. Using this constant means your map style
   * will always use the latest version and may change as we improve the style.
   */
  public static final String DARK = "mapbox://styles/mapbox/dark-v10";

```
But we cant seem to quite figure out how to do that when map tiles are downloaded from ```"https://maps.geo.${region}.amazonaws.com/maps/v0/maps/${mapName}/style-descriptor"``` instead.

Reference Screens (generated from the samples in this package)

| Android        | iOS           | 
| ------------- |:-------------:| 
| <img src="https://user-images.githubusercontent.com/3359983/119045060-d0c4d100-b96f-11eb-8773-2041521d9223.png" width="200" height="400" />      | <img src="https://user-images.githubusercontent.com/3359983/119045234-07025080-b970-11eb-9fa5-c4c6aa893dfc.png" width="200" height="400" /> |
| https://user-images.githubusercontent.com/3359983/119045051-cc98b380-b96f-11eb-9209-b9a231a9506f.mp4    |https://user-images.githubusercontent.com/3359983/119044587-3d8b9b80-b96f-11eb-87d0-3aeee2806809.mov      |   

https://user-images.githubusercontent.com/3359983/119045051-cc98b380-b96f-11eb-9209-b9a231a9506f.mp4

https://user-images.githubusercontent.com/3359983/119044587-3d8b9b80-b96f-11eb-87d0-3aeee2806809.mov

Any advice on this would be appreciated.

**Comment by mojodna** [comment]
This particular style doesn't have a background color set (so that it can be overlaid upon a hillshade layer), so it's inheriting the color of the view behind it as its background. To work around this, set the color of the view to white (as in the PR) to match the intended appearance.
