### ISSUE TITLE
[iOS] Calls to MGLOfflineStorageDelegate.offlineStorage block the main thread

### ISSUE THREAD

**Issue by PeterKaminski09** [aws-samples/amazon-location-samples#31]
I'm noticing sigV4 signing of the request in the `MGLOfflineStorageDelegate` blocks the main thread.

```
    func offlineStorage(_ storage: MGLOfflineStorage, urlForResourceOf kind: MGLResourceKind, with url: URL) -> URL {
        ...
        
        // sign the URL
        let task = AWSSignatureV4Signer
            .generateQueryStringForSignatureV4(
                withCredentialProvider: credentialsProvider,
                httpMethod: .GET,
                expireDuration: 60,
                endpoint: endpoint!,
                // workaround for https://github.com/aws-amplify/aws-sdk-ios/issues/3215
                keyPath: AWSSignatureV4Delegate.doubleEncode(path: percentEncodedKeyPath),
                requestHeaders: requestHeaders,
                requestParameters: .none,
                signBody: true)
        task.waitUntilFinished() // blocking call
       
   }
```
Logs:
`2021-05-21 17:05:29.010345-0700 Amazon Location Service Demo[70102:7533064] Warning: A long-running operation is being executed on the main thread.` 

It's concerning that the internals of Mapbox are invoking `offlineStorage` on the main thread. Is there a work around for this?

**Comment by PeterKaminski09** [comment]
Can confirm it is being invoked from the main thread:
![Screen Shot 2021-05-24 at 8 52 07 AM](https://user-images.githubusercontent.com/5935411/119373529-5c3eaa80-bc6d-11eb-825b-2af2868b25f6.png)

> MGLOfflineStorage implements a singleton (shared object) that manages offline packs and ambient caching. All of this class’s instance methods are asynchronous, reflecting the fact that offline resources are stored in a database.
According to the docs, it seems like these should be asynchronous calls so this may be an issue with Mapbox itself

**Comment by mojodna** [comment]
Thanks for opening the MapLibre Native issue. This is something we've noticed in the past and would like to address, if only to get to the bottom of the warning messages. We were originally thinking that exposing request transformation as an explicitly async thing would be preferable, but that may not be necessary.

https://github.com/maplibre/maplibre-gl-native/blob/ee94520bffeae2f6246284e1931d0cc1d615f708/platform/ios/platform/darwin/src/MGLOfflineStorage.mm#L104 suggests that it may be running on the "current" thread (`mbgl::Scheduler::GetCurrent()`) relative to where it was registered. If that's the case, a potential workaround may be to call `setDelegate` from a different thread (perhaps one dedicated to signing).

If you're able to try that (and it works), please report back and we'll update the sample + docs.

**Comment by PeterKaminski09** [comment]
I tried a few variations, setting a breakpoint in the `offlineStorage` method to see what thread it was invoked on:

### Synchronous dispatch from the main thread

*Code*
```
DispatchQueue.global(qos: .userInitiated).sync {
   MGLOfflineStorage.shared.delegate = signingDelegate
}
```
*Result*
`offlineStorage` invoked on the main thread

### Asynchronous dispatch from the main thread

*Code*
```
private let signingDispatchQueue = DispatchQueue(label: "MapViewOfflineStorageDelegateQueue")

signingDispatchQueue.async { [weak self] in
        guard let self = self, let delegate = self.signingDelegate else { return }
        MGLOfflineStorage.shared.delegate = delegate
}
```
*Result*
A EXC_BAD_ACCESS crash occurs
![Screen Shot 2021-05-25 at 9 26 48 AM](https://user-images.githubusercontent.com/5935411/119534165-76df5500-bd3b-11eb-9de0-3d0a69b59e1a.png)

Are there any other ways to intercept and sign the request outside of this delegate? How difficult is it to modify the delegate's interface to provide a dedicated dispatch queue to be used? Blocking the main thread leads to some undefined behavior that is preventing me from integrating with Mapbox/MapLibre.

**Comment by PeterKaminski09** [comment]
I think I might have found a viable workaround

**Relevant issue**
https://github.com/mapbox/mapbox-gl-native/issues/12026
**Related PR**
https://github.com/mapbox/mapbox-gl-native/pull/13886/files

Instead of signing requests via the delegate, I implemented my own `URLProtocol` that intercepted and signed the request.

You can add the interceptor via https://github.com/maplibre/maplibre-gl-native/blob/ee94520bffeae2f6246284e1931d0cc1d615f708/platform/ios/platform/darwin/src/MGLNetworkConfiguration.h#L64
```
var protocolClasses = [AnyClass]()
protocolClasses.append(MapboxURLProtocol.self)

let configuration = URLSessionConfiguration.default
configuration.protocolClasses = protocolClasses
        
MGLNetworkConfiguration.sharedManager.sessionConfiguration = configuration
```

**Comment by mojodna** [comment]
This is fascinating. The ability to provide a custom `URLSessionConfiguration` is totally new to me (and didn't exist the last time I was trying to achieve this, hence the use of the `OfflineStorageDelegate`).

Are you able to share your custom `URLProtocol`? That may be a better mechanism to use, document, and provide in some sort of helper library.

**Comment by mojodna** [comment]
@ameter could I trouble you for a pointer to your implementation of this so we can either update the example here (for folks who want to fully DIY) or point people in the right direction?

**Comment by PeterKaminski09** [comment]
I'll try to submit a pull request some time this week with my workaround.

**Comment by thehoneymad** [comment]
I am closing this in favour of closing the PR request out. @PeterKaminski09 , if this is still an issue, please reopen.
