### ISSUE TITLE
Docs for react-native usage

### ISSUE THREAD

**Issue by vamshi9666** [aws-samples/amazon-location-samples#56]
There is no documentation or guide about integrating aws location services in a react-native application.
Although in this [issue](https://github.com/aws-samples/amazon-location-samples/issues/8), @mojodna talked about native implementation, i believe there has to be a better way.

**Comment by mojodna** [comment]
What kind of better way do you have in mind? At some level, we need to bind to native iOS / Android (/ other) libraries.

**Comment by vamshi9666** [comment]
@mojodna  react-native-maps supports `UrlTile` component , but it won't cover entire usecase. May be some pre-request interceptor should be enough.
```
         <UrlTile
            transformRequest={(url) => Signer.sign(url)}
            urlTemplate={urlTemplate}
            maximumZ={19}
            flipY={false}
          />
```
 We can just fork `react-native-maps` for native networking inside module. 
I believe This makes integration straight forward.

**Comment by mojodna** [comment]
While `react-native-maps` supports `UrlTile`, it looks like it wraps the native map widgets on iOS (MapKit) and Android (Google Maps). If Amazon Location primarily returned tiles as images, this would probably be fine, but it returns vector data in MVT format and requires an additional renderer dependency (Mapbox GL / MapLibre / Tangram) to turn them into images.

I would love to be wrong, so if you're aware of an MVT-supporting renderer in that lib, please point me in its direction.

**Comment by thehoneymad** [comment]
Hello folks, I am closing this issue in favour of Amazon Location currently not supporting this. Please reopen the issue if we could be of more help.

**Comment by zali0** [comment]
Brothers, are there any updates regarding this issue?

**Comment by dreamorosi** [comment]
Hi @zali0, unfortunately at the moment we don't have any news to share regarding react-native support.
