### ISSUE TITLE
[Looking file, and format]

### ISSUE THREAD

**Issue by NguyenDOanNhan** [aws-samples/amazon-location-samples#89]
ex: amazon-location-samples/maplibre-js-react-iot-asset-tracking/
Integrating all resources to the web application
" Step 7 Under the Resources part of the cloudformation template, insert the policy that allow authenticated users to read Amazon Location resources:" 

sorry, The format you provided for the Resources section is not JSON.
Can you write a little more clearly?
Thank you for creating a great example, and I'm trying to do it

**Comment by dreamorosi** [comment]
Hello thank you for opening the issue, could you please elaborate more on what's the issue?

Are you referring to this step below?
![image](https://user-images.githubusercontent.com/7353869/151533288-e38cf254-31ba-4a3d-9e73-671588b4d598.png)

**Comment by NguyenDOanNhan** [comment]
Thanks for texting back
I'm trying to do step 7 but can't find the file you describe to include.
Can you share pictures of the steps you took in the tutorial?

**Comment by NguyenDOanNhan** [comment]
thank you i solved this problem!

**Comment by dreamorosi** [comment]
We have revisited the guide to now leverage Amplify CLI for most of the deployment and clarify some points.

Closing the issue since you solved it already in the meanwhile.
