### ISSUE TITLE
tracking-ios: asl_set_query is deprecated (os_log is the replacement).

### ISSUE THREAD

**Issue by jfischburg-lifemesh** [aws-samples/amazon-location-samples#90]
The solution will not build in XCode with support for iOS>=10 since asl_set_query has been replaced with os_log. Are there any plans to resolve this issue?

**Comment by jfischburg-lifemesh** [comment]
To clarify: The issue doesn't prevent building, build generates issues related to deprecating asl in favor of os_log.

**Comment by dreamorosi** [comment]
Hi @jfischburg-lifemesh, thanks for reporting this. If you'd like to open a PR I'd be happy to support you and merge it.
